[STRMCMP-1659] k8s 1.24 upgrade networking fix (#297)
## overview
networking.k8s.io/v1beta1 API versions of Ingress is no longer served as
of v1.22. upgrade to v1

Error: `Failed to create job managers for deploy 0cefa86b: no matches
for kind "Ingress" in version "networking.k8s.io/v1beta1"`